### PR TITLE
A little better wording for the alert box.

### PR DESCRIPTION
**Pull request by salt-lick**

### CODE REVIEW

**Comment by huberf** [comment]
Thanks!

**Comment by larrymason** [comment]
It would be better to use the pop-up dialogs to present this message so it
is consistent with the other dialog boxes. We have javascript and code in
the current client software to present this kind of information. We we
start having different sorts of (alert) dialog box our UI will look
scattered.

**Comment by salt-lick** [comment]
I agree @larrymason. A simple call to a div overlay would work better to display this information.

**Comment by larrymason** [comment]
it is already there that is what I'm trying to say...

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=glmason.lm@gmail.com&idSignature=22

**Pull request merged**
